--- #YAML:1.0
name:               Acme-Study-Perl
version:            0.0.1
abstract:           empirical studies about how perl behaves
author:
    - Andreas König <andreas.koenig.7os6VVqR@franz.ak.mind.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.4702
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
repository:         git://repo.or.cz/acme-study-perl.git
